FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps
WORKDIR /app/client
COPY packages/client/package*.json ./
RUN npm install

FROM base AS dev
WORKDIR /app/client
COPY packages/client ./
COPY --from=deps /app/client/node_modules ./node_modules
EXPOSE 5173
CMD ["npm", "run", "dev"]