FROM node:22-alpine AS base
WORKDIR /app

FROM base AS deps
COPY ../packages/server/package*.json ./
RUN --mount=type=cache,id=npm,target=/root/.npm \
    npm ci --omit=dev

FROM base AS dev
WORKDIR /app
COPY ../packages/server/package*.json ./
COPY --from=deps /app/node_modules ./node_modules
COPY ../packages/server ./
EXPOSE 3000
CMD ["sh", "-c", "npm run dev"]
