services:
  smart-class-server-prod:
    image: ${DOCKERHUB_USERNAME}/smart-class-server:latest
    expose:
      - "3000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@smart-class-db-prod:5432/${POSTGRES_DB}
      - DATA_API_URL=http://smart-class-data-prod:5001
    networks:
      - smart-class-network

  smart-class-db-prod:
    image: postgres:latest
    volumes:
      - "smart-class-db-postgres-data:/var/lib/postgresql/data:rw"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - "5432"
    restart: always
    networks:
      - smart-class-network

  smart-class-client-prod:
    image: ${DOCKERHUB_USERNAME}/smart-class-client:latest
    expose:
      - "5173"
    restart: always
    networks:
      - smart-class-network

  smart-class-data-prod:
    profiles:
      - data
    image: ${DOCKERHUB_USERNAME}/smart-class-data:latest
    expose:
      - "5001"
    restart: always
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@smart-class-db-prod:5432/${POSTGRES_DB}
      - FLASK_ENV=production
      - PORT=5001
      - SERVER_URL=http://smart-class-server-prod:3000
    depends_on:
      - smart-class-db-prod
    networks:
      - smart-class-network

volumes:
  smart-class-db-postgres-data:

networks:
  smart-class-network:
    driver: bridge