services:
  smart-class-server-dev:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.api.dev
    ports:
      - "3000:3000"
    volumes:
      - ../packages/server:/app
    networks:
      - smart-class-network

  smart-class-db:
    image: postgres:latest
    container_name: db
    volumes:
      - "smart-class-db-postgres-data:/var/lib/postgresql/data:rw"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=smartclass
      - POSTGRES_DB=smart-class
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - smart-class-network

volumes:
  smart-class-db-postgres-data:

networks:
  smart-class-network:
    driver: bridge
