FROM node:22-alpine AS base

WORKDIR /app

FROM base AS deps
COPY ../packages/server/package*.json ./
RUN npm install

FROM base AS dev
WORKDIR /app
COPY ../packages/server/package*.json ./
COPY --from=deps /app/node_modules ./node_modules
COPY ../packages/server ./
EXPOSE 3000
CMD ["npm", "run", "dev"]
