services:
  smart-class-server-dev:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.api.dev
    ports:
      - "3000:3000"
    volumes:
      - ../packages/server:/app
    networks:
      - smart-class-network
    environment:
      - DATABASE_URL=postgresql://smartclass:root@smart-class-db-dev:5432/smart-class

  smart-class-db-dev:
    image: postgres:latest
    volumes:
      - "smart-class-db-postgres-data:/var/lib/postgresql/data:rw"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=smartclass
      - POSTGRES_DB=smart-class
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - smart-class-network

  smart-class-client-dev:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.client.dev
    ports:
      - "5173:5173"
    volumes:
      - ../packages/client:/app/client
      - /app/client/node_modules
    networks:
      - smart-class-network

volumes:
  smart-class-db-postgres-data:

networks:
  smart-class-network:
    driver: bridge
