services:
  smart-class-server-dev:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.server.dev
    ports:
      - "3000:3000"
    volumes:
      - ../packages/server:/app/server
      - sm_dev_server_node_modules:/app/server/node_modules
    networks:
      - smart-class-network
    environment:
      - DATABASE_URL=postgresql://smartclass:root@smart-class-db-dev:5432/smart-class
      - JWT_SECRET=da024be3c25cc0134c2d5c207f1bad54
      - COOKIE_SECRET=secret-cookie-monster
      - MQTT_BROKER_URL=mqtt://admin-hetic.arcplex.tech:8823

  smart-class-db-dev:
    image: postgres:latest
    volumes:
      - "smart-class-db-postgres-data:/var/lib/postgresql/data:rw"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=smartclass
      - POSTGRES_DB=smart-class
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - smart-class-network

  smart-class-client-dev:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.client.dev
    ports:
      - "5173:5173"
    volumes:
      - ../packages/client:/app/client
      - sm_dev_client_node_modules:/app/client/node_modules
    networks:
      - smart-class-network

volumes:
  sm_dev_server_node_modules:
  smart-class-db-postgres-data:
  sm_dev_client_node_modules:

networks:
  smart-class-network:
    driver: bridge
