name: ci/cd

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone data service
        run: |
          git clone https://github.com/arasolonjatovo/smart-class-tdd.git packages/data

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push client image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/Dockerfile.client.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/smart-class-client:latest
          build-args: |
            VITE_API_URL=https://06.hetic.arcplex.dev/api

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/Dockerfile.server.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/smart-class-server:latest

      - name: Build and push data service image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/Dockerfile.data.prod
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/smart-class-data:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 2323
          source: "Docker/docker-compose.prod.yml,packages/server/drizzle.config.ts,packages/server/drizzle/,packages/server/database/"
          target: "/home/${{ secrets.VPS_USERNAME }}/smart-class/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 2323
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/smart-class/Docker

            docker compose -f docker-compose.prod.yml --profile data down || true

            docker pull ${{ vars.DOCKERHUB_USERNAME }}/smart-class-client:latest
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/smart-class-server:latest
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/smart-class-data:latest

            docker compose -f docker-compose.prod.yml --profile data up -d

            # Run database migrations
            echo "Running database migrations..."
            docker cp /home/${{ secrets.VPS_USERNAME }}/smart-class/packages/server/drizzle.config.ts docker-smart-class-server-prod-1:/app/
            docker cp /home/${{ secrets.VPS_USERNAME }}/smart-class/packages/server/drizzle docker-smart-class-server-prod-1:/app/
            docker exec docker-smart-class-server-prod-1 npm run db:migrate

            # Clean up unused images
            docker image prune -f

            echo "Deployment with migrations and database seeding completed!"
